# fly.toml app configuration file generated for tailwings on 2023-05-23T23:44:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ryo"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PORT = "41641"

[[services]]
  protocol = "udp"
  internal_port = 41641
  processes = ["app"]

  [[services.ports]]
    port = 41641
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 75
